/* ══════════════════════════════════════════════════════════
   MOCK DATA — full detail for ขาเข้า patients
   keyed by referId; matches MOCK_IN_DATA in ReferInPage.jsx
   ══════════════════════════════════════════════════════════ */

const SHARED_CLINICAL = {
  referralValidity:  { label: 'สำหรับการรักษาครั้งนี้เท่านั้น', color: 'magenta' },
  referralType:      { label: 'เพื่อการวินิจฉัยและรักษา', color: 'geekblue' },
  infectiousStatus:  { label: 'ไม่ได้เป็นโรคติดต่อ ( Non-Infective )', color: 'green' },
  emergencyLevel:    'non-acute',
  historyFamily:     '-',
  currentHistory:    '-',
  labResults:        '-',
  initialDiagnosis:  'HT in the young',
  treatmentGiven:    'FBC 200 mg 105 เม็ด กินครั้งละ 4 เม็ด',
  referralReason:    'รักษาต่อเนื่อง',
  otherDetails:      '-',
  vsDateTime:        '20/5/2568 - 16:12',
  painScore:         '5',
  temperature:       '38 °C',
  systolicBP:        '120 mmHg',
  diastolicBP:       '70 mmHg',
  pulseRate:         '70 bpm',
  respiratoryRate:   '24 bpm',
  o2Saturation:      '98%',
  icd9List: [
    {
      id:          'icd9-1',
      code:        '1021',
      name:        'Biopsy of conjunctiva',
      surgeryDate: '20/5/2568',
      anesthesia:  'การดมยาสลบ (General Anesthesia)',
      otherMethod: null,
      details:     '-',
    },
  ],
  icd10List: [
    { id: 'icd10-1', priority: 'Principal Diagnosis', code: 'I10', name: 'Essential (primary) hypertension' },
  ],
  allergyList: [
    {
      id:               'al-1',
      reportDate:       '02/03/2568',
      drugCode:         '629925',
      drugName:         '(SI) PARACETAMOL 120 MG/5 ML 60 ML SYRUP',
      allergyDiagnosis: 'Certain',
      severity:         'ไม่ร้ายแรง (Non-serious)',
    },
  ],
  txHistoryList: [
    {
      id:        'tx-1',
      drugCode:  '629925',
      drugName:  '(SI) PARACETAMOL 120 MG/5 ML 60 ML SYRUP',
      startDate: '02/03/2568',
      endDate:   '05/03/2568',
    },
  ],
}

function docs(n) {
  const p = String(n).padStart(3, '0')
  return {
    lab:   [{ id: `d-lab-${n}`,  name: `LAB_Result_${p}.png`     }],
    ekg:   [{ id: `d-ekg-${n}`,  name: `EKG_Report_${p}.pdf`     }],
    xray:  [{ id: `d-xr-${n}`,   name: `XRay_Chest_${p}.png`     }],
    mri:   [{ id: `d-mri-${n}`,  name: `MRI_Brain_${p}.pdf`      }],
    ct:    [{ id: `d-ct-${n}`,   name: `CT_Scan_Head_${p}.pdf`   }],
    other: [{ id: `d-oth-${n}`,  name: `Additional_Doc_${p}.pdf` }],
  }
}

export const MOCK_IN_PATIENTS = {
  '20300-256805-1': {
    ...SHARED_CLINICAL,
    referId:    '20300-256805-1',
    nationalId: '1-2201-33412-17-6',
    fullName:   'นายสมพงษ์ วิชาดี',
    status:     'received',
    prefix:          'นาย',
    firstName:       'สมพงษ์',
    lastName:        'วิชาดี',
    gender:          'ชาย',
    dateOfBirth:     '14/03/2510',
    hn:              'HN-2025-001',
    phone:           '081-234-5601',
    patientCategory: 'ผู้ป่วยทั่วไป',
    patientType:     'ผู้ป่วยนอก (OPD)',
    houseNo:         '12',   moo: '3',  road: 'สายเอเชีย',
    subDistrict:     'ประตูชัย', district: 'พระนครศรีอยุธยา', province: 'พระนครศรีอยุธยา', postalCode: '13000',
    nearbyLocation:  'ตลาดหัวรอ',
    referralDocNo:       '01/68',
    admissionDateTime:   '02/05/2568 - 09:00',
    sourceHospitalName:  'โรงพยาบาลพระนครศรีอยุธยา',
    sourceHospitalPhone: '035-322-555',
    destHospitalName:    'โรงพยาบาลใจสู้ลองรักษา',
    treatmentRight:      'สิทธิประกันสังคม (SSS)',
    rightNumber:         '22010 - 00001',
    billTo:              'โรงพยาบาลพระนครศรีอยุธยา',
    documents: docs(1),
  },

  '20300-256805-2': {
    ...SHARED_CLINICAL,
    referId:    '20300-256805-2',
    nationalId: '3-4503-22617-85-1',
    fullName:   'นางสาวรัตนา ดวงดี',
    status:     'done',
    prefix:          'นางสาว',
    firstName:       'รัตนา',
    lastName:        'ดวงดี',
    gender:          'หญิง',
    dateOfBirth:     '22/07/2535',
    hn:              'HN-2025-002',
    phone:           '089-234-5602',
    patientCategory: 'ผู้ป่วยทั่วไป',
    patientType:     'ผู้ป่วยใน (IPD)',
    houseNo:         '45',  moo: '2',  road: 'นิมมานเหมินท์',
    subDistrict:     'สุเทพ', district: 'เมืองเชียงใหม่', province: 'เชียงใหม่', postalCode: '50200',
    nearbyLocation:  'มหาวิทยาลัยเชียงใหม่',
    referralDocNo:       '02/68',
    admissionDateTime:   '03/05/2568 - 11:30',
    sourceHospitalName:  'โรงพยาบาลเชียงใหม่',
    sourceHospitalPhone: '053-935-000',
    destHospitalName:    'โรงพยาบาลใจสู้ลองรักษา',
    treatmentRight:      'สิทธิบัตรทอง (UC)',
    rightNumber:         '50020 - 00002',
    billTo:              'โรงพยาบาลเชียงใหม่',
    documents: docs(2),
  },

  '20300-256805-3': {
    ...SHARED_CLINICAL,
    referId:    '20300-256805-3',
    nationalId: '2-6704-41023-33-8',
    fullName:   'นายชัยวัฒน์ สุขสบาย',
    status:     'returnOk',
    prefix:          'นาย',
    firstName:       'ชัยวัฒน์',
    lastName:        'สุขสบาย',
    gender:          'ชาย',
    dateOfBirth:     '05/11/2518',
    hn:              'HN-2025-003',
    phone:           '087-234-5603',
    patientCategory: 'ผู้ป่วยเก่า',
    patientType:     'ผู้ป่วยนอก (OPD)',
    houseNo:         '7',   moo: '5',  road: 'กาญจนวนิช',
    subDistrict:     'บ่อยาง', district: 'เมืองสงขลา', province: 'สงขลา', postalCode: '90000',
    nearbyLocation:  'ตลาดสดสงขลา',
    referralDocNo:       '03/68',
    admissionDateTime:   '04/05/2568 - 08:45',
    sourceHospitalName:  'โรงพยาบาลสงขลานครินทร์',
    sourceHospitalPhone: '074-451-000',
    destHospitalName:    'โรงพยาบาลใจสู้ลองรักษา',
    treatmentRight:      'สิทธิราชการ (CSMBS)',
    rightNumber:         '67040 - 00003',
    billTo:              'โรงพยาบาลสงขลานครินทร์',
    documents: docs(3),
  },

  '20300-256805-4': {
    ...SHARED_CLINICAL,
    referId:    '20300-256805-4',
    nationalId: '5-8805-54231-60-3',
    fullName:   'นางวรรณา เพ็ชรงาม',
    status:     'returned',
    prefix:          'นาง',
    firstName:       'วรรณา',
    lastName:        'เพ็ชรงาม',
    gender:          'หญิง',
    dateOfBirth:     '30/04/2520',
    hn:              'HN-2025-004',
    phone:           '086-234-5604',
    patientCategory: 'ผู้ป่วยทั่วไป',
    patientType:     'ผู้ป่วยใน (IPD)',
    houseNo:         '88',  moo: '1',  road: 'มิตรภาพ',
    subDistrict:     'ในเมือง', district: 'เมืองขอนแก่น', province: 'ขอนแก่น', postalCode: '40000',
    nearbyLocation:  'ศาลหลักเมืองขอนแก่น',
    referralDocNo:       '04/68',
    admissionDateTime:   '05/05/2568 - 14:15',
    sourceHospitalName:  'โรงพยาบาลขอนแก่น',
    sourceHospitalPhone: '043-336-789',
    destHospitalName:    'โรงพยาบาลใจสู้ลองรักษา',
    treatmentRight:      'สิทธิบัตรทอง (UC)',
    rightNumber:         '88050 - 00004',
    billTo:              'โรงพยาบาลขอนแก่น',
    documents: docs(4),
  },

  '20300-256805-5': {
    ...SHARED_CLINICAL,
    referId:    '20300-256805-5',
    nationalId: '1-3306-67894-28-5',
    fullName:   'นายธนกฤต อารีรัก',
    status:     'sent',
    prefix:          'นาย',
    firstName:       'ธนกฤต',
    lastName:        'อารีรัก',
    gender:          'ชาย',
    dateOfBirth:     '18/09/2540',
    hn:              '-',
    phone:           '083-234-5605',
    patientCategory: 'ผู้ป่วยใหม่',
    patientType:     'ผู้ป่วยนอก (OPD)',
    houseNo:         '3',   moo: '7',  road: 'สุรนารี',
    subDistrict:     'ในเมือง', district: 'เมืองนครราชสีมา', province: 'นครราชสีมา', postalCode: '30000',
    nearbyLocation:  'อนุสาวรีย์ท้าวสุรนารี',
    referralDocNo:       '05/68',
    admissionDateTime:   '06/05/2568 - 10:00',
    sourceHospitalName:  'โรงพยาบาลมหาราชนครราชสีมา',
    sourceHospitalPhone: '044-235-000',
    destHospitalName:    'โรงพยาบาลใจสู้ลองรักษา',
    treatmentRight:      'สิทธิประกันสังคม (SSS)',
    rightNumber:         '33060 - 00005',
    billTo:              'โรงพยาบาลมหาราชนครราชสีมา',
    documents: docs(5),
  },

  '20300-256805-6': {
    ...SHARED_CLINICAL,
    referId:    '20300-256805-6',
    nationalId: '3-7107-78345-41-2',
    fullName:   'นางสาวจิรา มีมงคล',
    status:     'waitDoctor',
    prefix:          'นางสาว',
    firstName:       'จิรา',
    lastName:        'มีมงคล',
    gender:          'หญิง',
    dateOfBirth:     '02/01/2543',
    hn:              '-',
    phone:           '082-234-5606',
    patientCategory: 'ผู้ป่วยใหม่',
    patientType:     'ผู้ป่วยนอก (OPD)',
    houseNo:         '19',  moo: '4',  road: 'เลียบเนิน',
    subDistrict:     'วัดใหม่', district: 'เมืองจันทบุรี', province: 'จันทบุรี', postalCode: '22000',
    nearbyLocation:  'ตลาดล่างจันทบุรี',
    referralDocNo:       '06/68',
    admissionDateTime:   '07/05/2568 - 13:00',
    sourceHospitalName:  'โรงพยาบาลพระปกเกล้า',
    sourceHospitalPhone: '039-321-777',
    destHospitalName:    'โรงพยาบาลใจสู้ลองรักษา',
    treatmentRight:      'สิทธิบัตรทอง (UC)',
    rightNumber:         '71070 - 00006',
    billTo:              'โรงพยาบาลพระปกเกล้า',
    documents: docs(6),
  },

  '20300-256805-7': {
    ...SHARED_CLINICAL,
    referId:    '20300-256805-7',
    nationalId: '2-0208-89012-55-7',
    fullName:   'นายเกษม รุ่งเรือง',
    status:     'draft',
    prefix:          'นาย',
    firstName:       'เกษม',
    lastName:        'รุ่งเรือง',
    gender:          'ชาย',
    dateOfBirth:     '11/06/2508',
    hn:              'HN-2025-007',
    phone:           '091-234-5607',
    patientCategory: 'ผู้ป่วยเก่า',
    patientType:     'ผู้ป่วยใน (IPD)',
    houseNo:         '56',  moo: '9',  road: 'เพชรเกษม',
    subDistrict:     'หาดใหญ่', district: 'หาดใหญ่', province: 'สงขลา', postalCode: '90110',
    nearbyLocation:  'ตลาดกิมหยง',
    referralDocNo:       '07/68',
    admissionDateTime:   '08/05/2568 - 09:30',
    sourceHospitalName:  'โรงพยาบาลหาดใหญ่',
    sourceHospitalPhone: '074-273-000',
    destHospitalName:    'โรงพยาบาลใจสู้ลองรักษา',
    treatmentRight:      'สิทธิราชการ (CSMBS)',
    rightNumber:         '02080 - 00007',
    billTo:              'โรงพยาบาลหาดใหญ่',
    documents: docs(7),
  },

  '20300-256805-8': {
    ...SHARED_CLINICAL,
    referId:    '20300-256805-8',
    nationalId: '1-5609-90123-74-4',
    fullName:   'นางสุดา ลำเจียก',
    status:     'returnRejected',
    prefix:          'นาง',
    firstName:       'สุดา',
    lastName:        'ลำเจียก',
    gender:          'หญิง',
    dateOfBirth:     '25/12/2516',
    hn:              'HN-2025-008',
    phone:           '085-234-5608',
    patientCategory: 'ผู้ป่วยทั่วไป',
    patientType:     'ผู้ป่วยใน (IPD)',
    houseNo:         '33',  moo: '6',  road: 'ทหาร',
    subDistrict:     'หมากแข้ง', district: 'เมืองอุดรธานี', province: 'อุดรธานี', postalCode: '41000',
    nearbyLocation:  'หนองประจักษ์',
    referralDocNo:       '08/68',
    admissionDateTime:   '09/05/2568 - 15:45',
    sourceHospitalName:  'โรงพยาบาลอุดรธานี',
    sourceHospitalPhone: '042-245-555',
    destHospitalName:    'โรงพยาบาลใจสู้ลองรักษา',
    treatmentRight:      'สิทธิบัตรทอง (UC)',
    rightNumber:         '56090 - 00008',
    billTo:              'โรงพยาบาลอุดรธานี',
    documents: docs(8),
  },

  '20300-256805-9': {
    ...SHARED_CLINICAL,
    referId:    '20300-256805-9',
    nationalId: '5-9910-01234-89-9',
    fullName:   'นายวิชัย ประเสริฐ',
    status:     'cancelledSrc',
    prefix:          'นาย',
    firstName:       'วิชัย',
    lastName:        'ประเสริฐ',
    gender:          'ชาย',
    dateOfBirth:     '08/02/2525',
    hn:              '-',
    phone:           '093-234-5609',
    patientCategory: 'ผู้ป่วยใหม่',
    patientType:     'ผู้ป่วยนอก (OPD)',
    houseNo:         '21',  moo: '2',  road: 'เพชรเกษม',
    subDistrict:     'พระปฐมเจดีย์', district: 'เมืองนครปฐม', province: 'นครปฐม', postalCode: '73000',
    nearbyLocation:  'องค์พระปฐมเจดีย์',
    referralDocNo:       '09/68',
    admissionDateTime:   '10/05/2568 - 08:15',
    sourceHospitalName:  'โรงพยาบาลนครปฐม',
    sourceHospitalPhone: '034-254-990',
    destHospitalName:    'โรงพยาบาลใจสู้ลองรักษา',
    treatmentRight:      'สิทธิประกันสังคม (SSS)',
    rightNumber:         '99100 - 00009',
    billTo:              'โรงพยาบาลนครปฐม',
    documents: docs(9),
  },

  '20300-256805-10': {
    ...SHARED_CLINICAL,
    referId:    '20300-256805-10',
    nationalId: '3-1211-12345-96-6',
    fullName:   'นางสาวนันทนา สว่างใจ',
    status:     'cancelledDest',
    prefix:          'นางสาว',
    firstName:       'นันทนา',
    lastName:        'สว่างใจ',
    gender:          'หญิง',
    dateOfBirth:     '17/08/2545',
    hn:              '-',
    phone:           '094-234-5610',
    patientCategory: 'ผู้ป่วยใหม่',
    patientType:     'ผู้ป่วยนอก (OPD)',
    houseNo:         '66',  moo: '8',  road: 'พหลโยธิน',
    subDistrict:     'ปากเพรียว', district: 'เมืองสระบุรี', province: 'สระบุรี', postalCode: '18000',
    nearbyLocation:  'วัดพระพุทธฉาย',
    referralDocNo:       '10/68',
    admissionDateTime:   '11/05/2568 - 16:00',
    sourceHospitalName:  'โรงพยาบาลสระบุรี',
    sourceHospitalPhone: '036-222-999',
    destHospitalName:    'โรงพยาบาลใจสู้ลองรักษา',
    treatmentRight:      'สิทธิบัตรทอง (UC)',
    rightNumber:         '12110 - 00010',
    billTo:              'โรงพยาบาลสระบุรี',
    documents: docs(10),
  },

  '20300-256805-11': {
    ...SHARED_CLINICAL,
    referId:    '20300-256805-11',
    nationalId: '1-4312-23456-03-0',
    fullName:   'นายอภิชาติ กิตติวงศ์',
    status:     'deceased',
    prefix:          'นาย',
    firstName:       'อภิชาติ',
    lastName:        'กิตติวงศ์',
    gender:          'ชาย',
    dateOfBirth:     '03/05/2498',
    hn:              'HN-2025-011',
    phone:           '095-234-5611',
    patientCategory: 'ผู้ป่วยเก่า',
    patientType:     'ผู้ป่วยใน (IPD)',
    houseNo:         '9',   moo: '1',  road: 'สุขุมวิท',
    subDistrict:     'ท่าประดู่', district: 'เมืองระยอง', province: 'ระยอง', postalCode: '21000',
    nearbyLocation:  'ตลาดสดระยอง',
    referralDocNo:       '11/68',
    admissionDateTime:   '12/05/2568 - 07:45',
    sourceHospitalName:  'โรงพยาบาลระยอง',
    sourceHospitalPhone: '038-611-104',
    destHospitalName:    'โรงพยาบาลใจสู้ลองรักษา',
    treatmentRight:      'สิทธิราชการ (CSMBS)',
    rightNumber:         '43120 - 00011',
    billTo:              'โรงพยาบาลระยอง',
    documents: docs(11),
  },
}
